[package]
name = "chia-ssl"
version = "0.35.0"
edition = "2024"
license = "Apache-2.0"
description = "Chia SSL X.509 certificate generator"
authors = ["Brandon Haggstrom <b.haggstrom@chia.net>"]
homepage = "https://github.com/Chia-Network/chia_rs"
repository = "https://github.com/Chia-Network/chia_rs"

[lints]
workspace = true

[dependencies]
rand = { workspace = true }
rcgen = { workspace = true, features = ["pem", "x509-parser"] }
rsa = { workspace = true }
thiserror = { workspace = true }
time = { workspace = true }
